name: Terraform

on:
  push:
    branches:
      - main  # Run the workflow on push to main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # Specify the Terraform version

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -var 'AWS_ACCESS_KEY_ID=AKIAYHJANG7OWQOPC552' -var 'AWS_SECRET_ACCESS_KEY=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' -auto-approve

